[package]
name="file_ref"
version="0.1.2"
edition="2021"

[dependencies]
winapi={ version="0.3.9", features=["winbase", "fileapi", "handleapi", "winnt", "minwinbase", "synchapi", "errhandlingapi"], optional=true }

[features]
dir_monitor=["winapi"]